services:
  sqlserver:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_ordico
    environment:
      SA_PASSWORD: "Ordico2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: unless-stopped